# Generated by Django 6.0 on 2025-12-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegenerationtask',
            name='image_url',
        ),
        migrations.AddField(
            model_name='imagegenerationtask',
            name='content_type',
            field=models.CharField(default='image/png', max_length=100),
        ),
        migrations.AddField(
            model_name='imagegenerationtask',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
