# Generated by Django 6.0 on 2025-12-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_remove_imagegenerationtask_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegenerationtask',
            name='generation_type',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('direct', 'Direct')], default='automatic', max_length=20),
        ),
    ]
