# Generated by Django 6.0 on 2025-12-17 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_imagegenerationtask_generation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegenerationtask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='imagegenerationtask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
